on:
    push:
        branches:
            - main
            - dev
    
    
        paths:
            -"src/**"
    
    pull_request:
        branches:
            - main
            - dev

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: check code
          uses: actions/checkout@v7.0.1

        - name: run tests
          run: npm test

